# Generated by Django 5.1.2 on 2024-12-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search_do',
            name='description',
        ),
        migrations.AddField(
            model_name='search_do',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='search_do',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
